-- Generated by servant-elm
module API where

import Http
import Task
import Json.Decode as Decode

type alias Config = {
    baseURI : String
  , settings : Http.Settings
  }

type alias API a b l = {
    getUsers : Decode.Decoder a -> Task.Task Http.Error a
  , getDiscoveryById : Decode.Decoder b -> l -> Task.Task Http.Error b
  }

getAPI : Config -> API a b l
getAPI config = {
    getUsers = getUsers config
  , getDiscoveryById = getDiscoveryById config
  }


getUsers : Config -> Decode.Decoder a -> Task.Task Http.Error a
getUsers config decoder  =
  Http.send config.settings
        { verb = "GET"
        , headers = []
        , url = (config.baseURI ++ "/" ++ "users")
        , body = Http.empty
        } |> Http.fromJson decoder

getDiscoveryById : Config -> Decode.Decoder b -> l -> Task.Task Http.Error b
getDiscoveryById config decoder argId =
  Http.send config.settings
        { verb = "GET"
        , headers = []
        , url = (config.baseURI ++ "/" ++ "discovery" ++ "/"  ++ (toString argId))
        , body = Http.empty
        } |> Http.fromJson decoder
